name: HTML Validation

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # O la versión que prefieras

      - name: Install html-validator-cli
        run: npm install -g html-validator-cli

      - name: Validate HTML
        run: html-validator-cli doc/index.html --output json

